import assert from 'node:assert/strict';

import core from '@actions/core';

import getInputs from '../utils/get-inputs.js';

describe('utils/get-inputs', () => {
  const originalGetInput = core.getInput;
  const originalGetBooleanInput = core.getBooleanInput;
  const originalGetMultilineInput = core.getMultilineInput;
  const originalGithubActions = process.env.GITHUB_ACTIONS;
  const originalGithubToken = process.env.GITHUB_TOKEN;

  let inputValues;
  let booleanValues;
  let multilineValues;

  beforeEach(() => {
    inputValues = new Map();
    booleanValues = new Map();
    multilineValues = new Map();

    core.getInput = name => inputValues.get(name) ?? '';
    core.getBooleanInput = name => booleanValues.get(name) ?? false;
    core.getMultilineInput = name => multilineValues.get(name);
  });

  afterEach(() => {
    core.getInput = originalGetInput;
    core.getBooleanInput = originalGetBooleanInput;
    core.getMultilineInput = originalGetMultilineInput;

    if (originalGithubActions === undefined) {
      delete process.env.GITHUB_ACTIONS;
    } else {
      process.env.GITHUB_ACTIONS = originalGithubActions;
    }

    if (originalGithubToken === undefined) {
      delete process.env.GITHUB_TOKEN;
    } else {
      process.env.GITHUB_TOKEN = originalGithubToken;
    }
  });

  it('should use defaults when not running in GitHub Actions', () => {
    delete process.env.GITHUB_ACTIONS;
    process.env.GITHUB_TOKEN = 'token-from-env';

    inputValues.set('version', '1.2.3');
    multilineValues.set('commands', ['bun run build']);
    multilineValues.set('meta', ['FOO=bar']);
    multilineValues.set('sync-tags', ['v1']);
    multilineValues.set('update-files-meta', undefined);
    multilineValues.set('update-files-header', undefined);
    multilineValues.set('update-files', undefined);

    const result = getInputs();

    assert.equal(result.version, '1.2.3');
    assert.equal(result.bundleDependencies, false);
    assert.equal(result.landoPlugin, false);
    assert.equal(result.sync, false);
    assert.equal(result.root, process.cwd());
    assert.equal(result.syncBranch, 'main');
    assert.equal(result.syncEmail, 'github-actions@github.com');
    assert.equal(result.syncMessage, 'release v%s generated by @lando/prepare-release-action');
    assert.equal(result.syncToken, 'token-from-env');
    assert.equal(result.syncUsername, 'github-actions');
    assert.equal(result.versionMatch, 'v[0-9].*');
    assert.deepEqual(result.commands, ['bun run build']);
    assert.deepEqual(result.meta, ['FOO=bar']);
    assert.deepEqual(result.syncTags, ['v1']);
    assert.deepEqual(result.tokens, []);
    assert.deepEqual(result.updateHeader, []);
    assert.deepEqual(result.updateFiles, []);
    assert.deepEqual(result.credFiles, []);
  });

  it('should read booleans and explicit values in GitHub Actions', () => {
    process.env.GITHUB_ACTIONS = 'true';
    delete process.env.GITHUB_TOKEN;

    inputValues.set('version', '2.0.0');
    inputValues.set('root', '/tmp/workspace');
    inputValues.set('sync-branch', 'release');
    inputValues.set('sync-email', 'bot@example.com');
    inputValues.set('sync-message', 'syncing %s');
    inputValues.set('sync-token', 'token-from-input');
    inputValues.set('sync-username', 'release-bot');
    inputValues.set('version-match', '^v\\d+');

    booleanValues.set('bundle-dependencies', true);
    booleanValues.set('lando-plugin', true);
    booleanValues.set('sync', true);

    multilineValues.set('commands', ['bun run lint', 'bun run build']);
    multilineValues.set('meta', ['KEY=value']);
    multilineValues.set('sync-tags', ['stable', 'latest']);
    multilineValues.set('update-files-meta', ['A=1']);
    multilineValues.set('update-files-header', ['## Header']);
    multilineValues.set('update-files', ['CHANGELOG.md']);

    const result = getInputs();

    assert.equal(result.version, '2.0.0');
    assert.equal(result.bundleDependencies, true);
    assert.equal(result.landoPlugin, true);
    assert.equal(result.sync, true);
    assert.equal(result.root, '/tmp/workspace');
    assert.equal(result.syncBranch, 'release');
    assert.equal(result.syncEmail, 'bot@example.com');
    assert.equal(result.syncMessage, 'syncing %s');
    assert.equal(result.syncToken, 'token-from-input');
    assert.equal(result.syncUsername, 'release-bot');
    assert.equal(result.versionMatch, '^v\\d+');
    assert.deepEqual(result.commands, ['bun run lint', 'bun run build']);
    assert.deepEqual(result.meta, ['KEY=value']);
    assert.deepEqual(result.syncTags, ['stable', 'latest']);
    assert.deepEqual(result.tokens, ['A=1']);
    assert.deepEqual(result.updateHeader, ['## Header']);
    assert.deepEqual(result.updateFiles, ['CHANGELOG.md']);
  });
});
