import assert from 'node:assert/strict';

import getInputs from '../utils/get-inputs.js';

describe('utils/get-inputs', () => {
  const originalGithubActions = process.env.GITHUB_ACTIONS;
  const originalGithubToken = process.env.GITHUB_TOKEN;
  const inputEnvNames = [
    'INPUT_VERSION',
    'INPUT_BUNDLE-DEPENDENCIES',
    'INPUT_COMMANDS',
    'INPUT_META',
    'INPUT_ROOT',
    'INPUT_SYNC',
    'INPUT_SYNC-BRANCH',
    'INPUT_SYNC-EMAIL',
    'INPUT_SYNC-VERIFIED',
    'INPUT_SYNC-MESSAGE',
    'INPUT_SYNC-TAGS',
    'INPUT_SYNC-TOKEN',
    'INPUT_SYNC-USERNAME',
    'INPUT_UPDATE-FILES-META',
    'INPUT_UPDATE-FILES-HEADER',
    'INPUT_UPDATE-FILES',
    'INPUT_VERSION-MATCH',
  ];

  beforeEach(() => {
    for (const name of inputEnvNames) {
      delete process.env[name];
    }
  });

  afterEach(() => {
    for (const name of inputEnvNames) {
      delete process.env[name];
    }

    if (originalGithubActions === undefined) {
      delete process.env.GITHUB_ACTIONS;
    } else {
      process.env.GITHUB_ACTIONS = originalGithubActions;
    }

    if (originalGithubToken === undefined) {
      delete process.env.GITHUB_TOKEN;
    } else {
      process.env.GITHUB_TOKEN = originalGithubToken;
    }
  });

  it('should use defaults when not running in GitHub Actions', () => {
    delete process.env.GITHUB_ACTIONS;
    process.env.GITHUB_TOKEN = 'token-from-env';

    process.env.INPUT_VERSION = '1.2.3';
    process.env.INPUT_COMMANDS = 'bun run build';
    process.env.INPUT_META = 'FOO=bar';
    process.env['INPUT_SYNC-TAGS'] = 'v1';

    const result = getInputs();

    assert.equal(result.version, '1.2.3');
    assert.equal(result.bundleDependencies, false);
    assert.equal(result.sync, false);
    assert.equal(result.root, process.cwd());
    assert.equal(result.syncBranch, 'main');
    assert.equal(result.syncEmail, '41898282+github-actions[bot]@users.noreply.github.com');
    assert.equal(result.syncVerified, false);
    assert.equal(result.syncMessage, 'release %s generated by @tanaabased/prepare-release-action');
    assert.equal(result.syncToken, 'token-from-env');
    assert.equal(result.syncUsername, 'github-actions[bot]');
    assert.equal(result.versionMatch, 'v[0-9].*');
    assert.deepEqual(result.commands, ['bun run build']);
    assert.deepEqual(result.meta, ['FOO=bar']);
    assert.deepEqual(result.syncTags, ['v1']);
    assert.deepEqual(result.tokens, []);
    assert.deepEqual(result.updateHeader, []);
    assert.deepEqual(result.updateFiles, []);
    assert.deepEqual(result.credFiles, []);
  });

  it('should read booleans and explicit values in GitHub Actions', () => {
    process.env.GITHUB_ACTIONS = 'true';
    delete process.env.GITHUB_TOKEN;

    process.env.INPUT_VERSION = '2.0.0';
    process.env.INPUT_ROOT = '/tmp/workspace';
    process.env['INPUT_SYNC-BRANCH'] = 'release';
    process.env['INPUT_SYNC-EMAIL'] = 'bot@example.com';
    process.env['INPUT_SYNC-MESSAGE'] = 'syncing %s';
    process.env['INPUT_SYNC-TOKEN'] = 'token-from-input';
    process.env['INPUT_SYNC-USERNAME'] = 'release-bot';
    process.env['INPUT_VERSION-MATCH'] = '^v\\d+';
    process.env['INPUT_BUNDLE-DEPENDENCIES'] = 'true';
    process.env.INPUT_SYNC = 'true';
    process.env['INPUT_SYNC-VERIFIED'] = 'true';
    process.env.INPUT_COMMANDS = ['bun run lint', 'bun run build'].join('\n');
    process.env.INPUT_META = 'KEY=value';
    process.env['INPUT_SYNC-TAGS'] = ['stable', 'latest'].join('\n');
    process.env['INPUT_UPDATE-FILES-META'] = 'A=1';
    process.env['INPUT_UPDATE-FILES-HEADER'] = '## Header';
    process.env['INPUT_UPDATE-FILES'] = 'CHANGELOG.md';

    const result = getInputs();

    assert.equal(result.version, '2.0.0');
    assert.equal(result.bundleDependencies, true);
    assert.equal(result.sync, true);
    assert.equal(result.root, '/tmp/workspace');
    assert.equal(result.syncBranch, 'release');
    assert.equal(result.syncEmail, 'bot@example.com');
    assert.equal(result.syncVerified, true);
    assert.equal(result.syncMessage, 'syncing %s');
    assert.equal(result.syncToken, 'token-from-input');
    assert.equal(result.syncUsername, 'release-bot');
    assert.equal(result.versionMatch, '^v\\d+');
    assert.deepEqual(result.commands, ['bun run lint', 'bun run build']);
    assert.deepEqual(result.meta, ['KEY=value']);
    assert.deepEqual(result.syncTags, ['stable', 'latest']);
    assert.deepEqual(result.tokens, ['A=1']);
    assert.deepEqual(result.updateHeader, ['## Header']);
    assert.deepEqual(result.updateFiles, ['CHANGELOG.md']);
  });
});
