import * as core from '@actions/core';

const defaultSyncBranch = 'main';
const defaultSyncEmail = '41898282+github-actions[bot]@users.noreply.github.com';
const defaultSyncMessage = 'release %s generated by @tanaabased/prepare-release-action';
const defaultSyncUsername = 'github-actions[bot]';
const defaultVersionMatch = 'v[0-9].*';

export default () => ({
  // required inputs
  version: String(core.getInput('version')),

  // optional inputs
  bundleDependencies: process.env.GITHUB_ACTIONS
    ? core.getBooleanInput('bundle-dependencies')
    : false,
  commands: core.getMultilineInput('commands'),
  credFiles: [],
  meta: core.getMultilineInput('meta'),
  root: core.getInput('root') || process.cwd(),
  sync: process.env.GITHUB_ACTIONS ? core.getBooleanInput('sync') : false,
  syncBranch: core.getInput('sync-branch') || defaultSyncBranch,
  syncEmail: core.getInput('sync-email') || defaultSyncEmail,
  syncVerified: process.env.GITHUB_ACTIONS ? core.getBooleanInput('sync-verified') : false,
  syncMessage: core.getInput('sync-message') || defaultSyncMessage,
  syncTags: core.getMultilineInput('sync-tags'),
  syncToken: core.getInput('sync-token') || process.env.GITHUB_TOKEN,
  syncUsername: core.getInput('sync-username') || defaultSyncUsername,
  tokens: core.getMultilineInput('update-files-meta') ?? [],
  updateHeader: core.getMultilineInput('update-files-header') ?? [],
  updateFiles: core.getMultilineInput('update-files') ?? [],
  versionMatch: core.getInput('version-match') || defaultVersionMatch,
});
