name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-24.04
          - macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Run unit tests
        run: bun run test
