name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install deps and prep
        run: |
          bun install --frozen-lockfile --ignore-scripts
          bun run lint
          bun run test
          bun run build
      - name: Export formatted release date
        run: echo "RELEASE_DATE=$(date -d "${{ github.event.release.published_at }}" "+%B %e, %Y" | tr -s ' ')" >> $GITHUB_ENV
      - name: Prepare release
        uses: ./
        with:
          commands: bun run build
          sync-tags: v3
          sync-token: ${{ secrets.TANAAB_COAXIUM_INJECTOR }}
          sync-email: tanaabot@tanaab.dev
          sync-username: tanaabot
          update-files: CHANGELOG.md
          update-files-header: |
            ## {{ UNRELEASED_VERSION }} - [{{ UNRELEASED_DATE }}]({{ UNRELEASED_LINK }})
          update-files-meta: |
            UNRELEASED_DATE=${{ env.RELEASE_DATE }}
            UNRELEASED_LINK=${{ github.event.release.html_url }}
            UNRELEASED_VERSION=${{ github.event.release.tag_name }}
